# Generated by Django 4.2 on 2023-04-24 07:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriasImplementos",
            fields=[
                ("IdCategoria", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="EstadoImplemento",
            fields=[
                ("IdEstado", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Estudiantes",
            fields=[
                (
                    "CodigoEstudiante",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Correo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ImplementosDeportivos",
            fields=[
                ("Idimplemento", models.AutoField(primary_key=True, serialize=False)),
                ("Marca", models.CharField(max_length=20)),
                ("Disponibilidad", models.BooleanField()),
                (
                    "IdCategoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.categoriasimplementos",
                    ),
                ),
                (
                    "IdEstado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.estadoimplemento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prestamos",
            fields=[
                ("IdPrestamo", models.AutoField(primary_key=True, serialize=False)),
                ("FechaPrestamo", models.DateTimeField()),
                ("FechaDevolucion", models.DateTimeField()),
                (
                    "IdEstudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.estudiantes",
                    ),
                ),
                (
                    "IdImplemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.implementosdeportivos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TiposDeMulta",
            fields=[
                ("IdTipo", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=20)),
                ("Valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("CodigoUsuario", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=20)),
                ("Clave", models.CharField(max_length=20)),
                ("Rol", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Reservas",
            fields=[
                ("IdReserva", models.AutoField(primary_key=True, serialize=False)),
                ("FechaDeSolicitud", models.DateTimeField()),
                ("Aprobado", models.BooleanField(null=True)),
                (
                    "IdImplemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.implementosdeportivos",
                    ),
                ),
                (
                    "IdPrestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.prestamos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multas",
            fields=[
                ("IdMulta", models.AutoField(primary_key=True, serialize=False)),
                ("Sancion", models.CharField(max_length=20)),
                ("Descripcion", models.TextField(max_length=200)),
                ("Pagada", models.BooleanField()),
                (
                    "IdEstudiantes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.estudiantes",
                    ),
                ),
                (
                    "IdTipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tiposdemulta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Funcionarios",
            fields=[
                (
                    "CodigoFuncionario",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Documento", models.CharField(max_length=20, unique=True)),
                (
                    "Usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.usuarios",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="estudiantes",
            name="Usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.usuarios"
            ),
        ),
        migrations.CreateModel(
            name="Administradores",
            fields=[
                (
                    "CodigoAdministradores",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Documento", models.IntegerField(unique=True)),
                (
                    "Usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.usuarios",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Devoluciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FechaEntrega", models.DateTimeField()),
                ("prestamo", models.IntegerField()),
                (
                    "IDestudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.estudiantes",
                    ),
                ),
                (
                    "IDimplemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.implementosdeportivos",
                    ),
                ),
            ],
            options={
                "unique_together": {("IDestudiante", "IDimplemento")},
            },
        ),
    ]
