# Generated by Django 4.2 on 2023-05-16 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriasImplementos",
            fields=[
                ("IdCategoria", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="EstadoImplemento",
            fields=[
                ("IdEstado", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ImplementosDeportivos",
            fields=[
                ("Idimplemento", models.AutoField(primary_key=True, serialize=False)),
                ("Marca", models.CharField(max_length=20)),
                ("Disponibilidad", models.BooleanField()),
                (
                    "IdCategoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudiante.categoriasimplementos",
                    ),
                ),
                (
                    "IdEstado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudiante.estadoimplemento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prestamos",
            fields=[
                ("IdPrestamo", models.AutoField(primary_key=True, serialize=False)),
                ("FechaPrestamo", models.DateTimeField()),
                ("FechaDevolucion", models.DateTimeField()),
                (
                    "IdEstudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "IdImplemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudiante.implementosdeportivos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TiposDeMulta",
            fields=[
                ("IdTipo", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=20)),
                ("Valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Reservas",
            fields=[
                ("IdReserva", models.AutoField(primary_key=True, serialize=False)),
                ("FechaDeSolicitud", models.DateTimeField()),
                ("Aprobado", models.BooleanField(null=True)),
                (
                    "IdImplemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudiante.implementosdeportivos",
                    ),
                ),
                (
                    "IdPrestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudiante.prestamos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multas",
            fields=[
                ("IdMulta", models.AutoField(primary_key=True, serialize=False)),
                ("Sancion", models.CharField(max_length=20)),
                ("Descripcion", models.TextField(max_length=200)),
                ("Pagada", models.BooleanField()),
                (
                    "IdEstudiantes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "IdTipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudiante.tiposdemulta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Devoluciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FechaEntrega", models.DateTimeField()),
                ("prestamo", models.IntegerField()),
                (
                    "IDestudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "IDimplemento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudiante.implementosdeportivos",
                    ),
                ),
            ],
            options={
                "unique_together": {("IDestudiante", "IDimplemento")},
            },
        ),
    ]
