# Generated by Django 4.2 on 2023-05-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudiante", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="implementosdeportivos",
            name="IdEstado",
        ),
        migrations.AddField(
            model_name="prestamos",
            name="Estado",
            field=models.CharField(
                choices=[
                    ("prestamo", "En préstamo"),
                    ("devuelto", "Devuelto"),
                    ("vencido", "Vencido"),
                ],
                default="prestamo",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="EstadoImplemento",
        ),
    ]
