# Generated by Django 4.2 on 2023-05-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estudiante", "0002_remove_implementosdeportivos_idestado_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoriasimplementos",
            old_name="IdCategoria",
            new_name="id_categoria",
        ),
        migrations.RenameField(
            model_name="categoriasimplementos",
            old_name="Nombre",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="implementosdeportivos",
            old_name="Disponibilidad",
            new_name="disponibilidad",
        ),
        migrations.RenameField(
            model_name="implementosdeportivos",
            old_name="IdCategoria",
            new_name="id_categoria",
        ),
        migrations.RenameField(
            model_name="implementosdeportivos",
            old_name="Idimplemento",
            new_name="id_implemento",
        ),
        migrations.RenameField(
            model_name="implementosdeportivos",
            old_name="Marca",
            new_name="marca",
        ),
    ]
