# Generated by Django 4.2 on 2023-05-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_estudiantes_usuario_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="devoluciones",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="devoluciones",
            name="IDestudiante",
        ),
        migrations.RemoveField(
            model_name="devoluciones",
            name="IDimplemento",
        ),
        migrations.RemoveField(
            model_name="implementosdeportivos",
            name="IdCategoria",
        ),
        migrations.RemoveField(
            model_name="implementosdeportivos",
            name="IdEstado",
        ),
        migrations.RemoveField(
            model_name="multas",
            name="IdEstudiantes",
        ),
        migrations.RemoveField(
            model_name="multas",
            name="IdTipo",
        ),
        migrations.RemoveField(
            model_name="prestamos",
            name="IdEstudiante",
        ),
        migrations.RemoveField(
            model_name="prestamos",
            name="IdImplemento",
        ),
        migrations.RemoveField(
            model_name="reservas",
            name="IdImplemento",
        ),
        migrations.RemoveField(
            model_name="reservas",
            name="IdPrestamo",
        ),
        migrations.DeleteModel(
            name="CategoriasImplementos",
        ),
        migrations.DeleteModel(
            name="Devoluciones",
        ),
        migrations.DeleteModel(
            name="EstadoImplemento",
        ),
        migrations.DeleteModel(
            name="ImplementosDeportivos",
        ),
        migrations.DeleteModel(
            name="Multas",
        ),
        migrations.DeleteModel(
            name="Prestamos",
        ),
        migrations.DeleteModel(
            name="Reservas",
        ),
        migrations.DeleteModel(
            name="TiposDeMulta",
        ),
    ]
